## NumPy (Numerical Python) 

- Is an open source Python library(collection of code that makes tasks more easy) that’s widely used in science and engineering. 

- The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

# Check if pip is installed 
pip --version


# how to install pip?
Windows: py get-pip.py  || py -m pip install --upgrade pip


# how to install numpy library?
pip install numpy --> terminal

"""
pip is the package installer for Python. You can use pip to install packages from the Python Package Index and other indexes.

"""

# how to import libraries in python?
import numpy as np

In [1]:
import numpy as np # as is alias

In [2]:
# When to use numpy?
# NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.


In [3]:
lists = [1,2,3,5,6,"Dev",3.0]
lists

[1, 2, 3, 5, 6, 'Dev', 3.0]

In [4]:
# Numpy Array
nparray = np.array([1,2,3,4,5,6,"Dev", 4,5,12, 123]) 
nparray

# U21 - Unicode 21 Numpy type

array(['1', '2', '3', '4', '5', '6', 'Dev', '4', '5', '12', '123'],
      dtype='<U21')

In [5]:
nparray[0]

'1'

In [6]:
nparray[7]

'4'

In [7]:
nparray[:6] # Starts from 0 and goes till (6-1)

array(['1', '2', '3', '4', '5', '6'], dtype='<U21')

In [8]:
nparray[0] = 30
nparray

array(['30', '2', '3', '4', '5', '6', 'Dev', '4', '5', '12', '123'],
      dtype='<U21')

In [9]:
nparray = np.array([1,2,3,4,5,6,7,8,9])

In [10]:
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(nparray)

numpy.ndarray

In [12]:
# List Vs numpyarray
# Convert list l = [1,2,3,4,5,6,7,8] into numpy array
l = [1,2,3,4,5,6,7,8]
ndarray = np.array([1,2,3,4,5,6,7,8])

In [13]:
ndarray

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
type(ndarray)

numpy.ndarray

In [15]:
# ndim - number of dimensions
ndarray.ndim

1

In [16]:
#shape - shape of the numpy array
ndarray.shape

(8,)

In [17]:
# size
ndarray.size

8

In [18]:
ndarray.dtype

dtype('int64')

In [19]:
#1-D Vs 2-D lists 
lists = [1,2,3,4,5]
list2 = [[1,2,3,4,5],[6,7,8,9,10]]
lists
#list2

[1, 2, 3, 4, 5]

In [20]:
# 2-D numpy array
ndarray2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [21]:
ndarray2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
ndarray2.ndim

2

In [23]:
ndarray2.size

15

In [24]:
ndarray2.shape

(3, 5)

In [25]:
ndarray2.dtype

dtype('int64')

### Scenarios

In [26]:
# Create a array of all zeros
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
# Create a array of all one's
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# Create an empty array 
np.empty(9)

# Problem --> 

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
# Create a array of evenly spaced intervals elements
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [30]:
# Create an array with values that are spaced linearly in a specified interval
np.linspace(0, 20, num=6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [31]:
ndarray3 = np.array([34,56,43,23,45,87,89])

In [32]:
ndarray3

array([34, 56, 43, 23, 45, 87, 89])

In [33]:
np.sort(ndarray3) # default - ascending
# Descending Order

array([23, 34, 43, 45, 56, 87, 89])

In [34]:
# Descending Order

In [35]:
# Create two numpy arrays nd1 and nd2
nd1 = np.array([[1,2,31],[3,4,5]])
nd2 = np.array([[6,7,21],[8,9,10]])
nd2


array([[ 6,  7, 21],
       [ 8,  9, 10]])

In [36]:
# axis=0 means rows - horizontal                        rows and coloumns
np.concatenate((nd1,nd2), axis = 0)

array([[ 1,  2, 31],
       [ 3,  4,  5],
       [ 6,  7, 21],
       [ 8,  9, 10]])

In [37]:
# axis=1 means coloumns - vertical

#nd1 = np.array([[1,2,31],[3,4,5]])
#nd2 = np.array([[6,7,21],[8,9,10]])

np.concatenate((nd1,nd2), axis = 1)

array([[ 1,  2, 31,  6,  7, 21],
       [ 3,  4,  5,  8,  9, 10]])

In [38]:
# Can you convert 1-D into 2-D arrays or vise-a-versa
nd1 = np.array([1,2,31,3,4,5])

In [39]:
nd1

array([ 1,  2, 31,  3,  4,  5])

In [40]:
nd1.reshape(3,2)

array([[ 1,  2],
       [31,  3],
       [ 4,  5]])

In [41]:
nd1.reshape(2,3)

array([[ 1,  2, 31],
       [ 3,  4,  5]])

In [42]:
nd1.reshape(6,1)

array([[ 1],
       [ 2],
       [31],
       [ 3],
       [ 4],
       [ 5]])

In [43]:
nd1 = np.array([1,2,31,3,4,5])
nd1[:]

array([ 1,  2, 31,  3,  4,  5])

In [44]:
nd1[:3]

array([ 1,  2, 31])

In [45]:
nd1[3:]

array([3, 4, 5])

In [46]:
nd1[-2:]

array([4, 5])

In [47]:
# nd1 = np.array([1,2,31,3,4,5])

[nd1<8]

[array([ True,  True, False,  True,  True,  True])]

In [51]:
nd2 = np.array([0,1,2,31,3,4,5])

In [52]:
nd2

array([ 0,  1,  2, 31,  3,  4,  5])

In [53]:
# Check this---
nd2.nonzero()

(array([1, 2, 3, 4, 5, 6]),)

In [57]:
nd3 = np.array([0,1,2,3,54])

In [58]:
nd3

array([ 0,  1,  2,  3, 54])

In [59]:
nd3.nonzero()

(array([1, 2, 3, 4]),)

In [60]:
nd3

array([ 0,  1,  2,  3, 54])

In [67]:
nd3=nd3*2
nd3

array([  0,   4,   8,  12, 216])

In [62]:
nd3.min()

0

In [63]:
nd3.max()

54

In [68]:
nd3.sum()

240

## Intersting Stuff

In [72]:
import random as rng

In [79]:
# random integer number matrix

rng.randint(15,4,2)

TypeError: Random.randint() takes 3 positional arguments but 4 were given